name: tweet_sche

description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  hive:
  hive_flutter: ^0.3.1
  firebase_storage:
  firebase_core:
  firebase_auth:
  cloud_firestore:

  cached_network_image:
  intl:
  eva_icons_flutter:
  flutter_svg: ^0.18.1
  dio:
  flutter_vector_icons:
  path_provider:
  loading_overlay:
  table_calendar:
  url_launcher:
  flushbar:
  flutter_staggered_grid_view: ^0.3.2
  image_picker:
  giphy_picker: ^1.0.8
 # file_picker:
  excel:

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.7.3
  hive_generator:

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: AvenirNext
      fonts:
        - asset: assets/fonts/AvenirNext.otf
    - family: Raleway
      fonts:
        - asset: assets/fonts/raleway.ttf